baseurl = "site url"
title = "LX Ramblings"
languageCode = "en"
copyright = "Copyright right infomation."
themesdir = "themes"
theme = "hugo_eiio"
Paginate=15 
MetaDataFormat = "toml"
PaginatePath="page"
pygmentsuseclasses = true
hasCJKLanguage = false
preserveTaxonomyNames = false
disablePathToLower =false 
enableEmoji = false
enableInlineShortcodes = true
enableRobotsTXT = false

[taxonomies]
  category = "categories"
  tag = "tags"
  summaryLength = 250 # default 70
[params]
  hljsStyle="github" #code highlightjs css style . See [Style List](https://github.com/highlightjs/highlight.js/tree/master/src/styles "CSS Style list")
  showNextAndPrePosts = true #Is Show Next and Previous Post Button
  description = "Notes and other useful things"
  keywords = "site keywords use seo"
  author = "LX"
  securityPolicy = true #disable https content security policy

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
